### ISSUE TITLE
One bar graph missing

### ISSUE THREAD

**Issue by bengalspice** [PhilippBrugger/musclehub#1]
> In [ ]:
ax = plt.subplot()
plt.bar(range(len(app_pivot)),
       app_pivot['Percent with Application'].values)
ax.set_xticks(range(len(app_pivot)))
ax.set_xticklabels(['Fitness Test', 'No Fitness Test'])
ax.set_yticks([0, 0.05, 0.10, 0.15, 0.20])
ax.set_yticklabels(['0%', '5%', '10%', '15%', '20%'])
plt.show()
plt.savefig('percent_visitors_apply.png')

It appears that the code for the bar graph of members that apply wasn't run before submitting the final project file.  The code is otherwise correct. It's a simple oversight that even I have made in the past. If there's ever a doubt whether all the code has run, don't hesitate to rerun all your code before finalizing the jupyter notebook file for posting to GitHub.

**Comment by PhilippBrugger** [comment]
Thanks, I have adjusted that. I'll try and make this a habit ;-)
