### ISSUE TITLE
sql-query only needs to be imported once

### ISSUE THREAD

**Issue by bengalspice** [PhilippBrugger/musclehub#2]
>In [27]:
Examine visits here
from codecademySQL import sql_query
sql_query('''
SELECT *
FROM visits
LIMIT 5
''')

The special Codecademy library for SQL only needs to be imported once in Jupyter notebook. Be mindful of adding extra code to prevent any potential coding errors in the future.

**Comment by PhilippBrugger** [comment]
Hi, I've understood in the slack community that this might cause problems, but I can try.
