### ISSUE TITLE
Chi Square contingency

### ISSUE THREAD

**Issue by bengalspice** [PhilippBrugger/musclehub#3]
> from scipy.stats import chi2_contingency
X = [[250, 2254],
     [325, 2175]]
chi2, pval, dof, expected = chi2_contingency(X)
print pval 

When running the Chi Square test, you can simply run chi2_contingency(X) on it's own (without specifying chi2, pval, dof, expected) to find value of pval. This may make for cleaner code that's easy to follow for those who aren't familiar with what chi2, pval, dof, expected stand for.

**Comment by PhilippBrugger** [comment]
I have replaced chi2, pval, dof, expected = chi2_contingency(X) with chi2_contingency(X) which got me "repeated" results from the previous Chi Square tests. So I went back to this solution which seems to work more stable. Any idea what might be the issue?

**Comment by bengalspice** [comment]
chi2_contingency(x) on it's own should generate the values for chi2, pval, dof, expected. The second value you receive will be the pval, so you wouldn't then need to print pval to get the result.
So the code would look like: 
input: chi2_contingency(X)
output: (10.893961295282612,
 **0.00096478276007223038**,
 1,
 array([[  287.72981615,  2216.27018385],
        [  287.27018385,  2212.72981615]]))

The bolded value is pval

**Comment by PhilippBrugger** [comment]
Ok, now it works. I've simplified my code.
